# Generated by Django 6.0.7 on 2026-09-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=150)),
                ('team_b', models.CharField(max_length=150)),
                ('score_a', models.CharField(default=0)),
                ('score_b', models.CharField(default=0)),
            ],
        ),
    ]
